queue:
  name: Hosted macOS
  demands: msbuild

variables:
  BuildConfiguration: 'Release'
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
steps:
#- script: |
#   echo install objective sharpie
#   brew cask install objectivesharpie
#   echo Performing make
#   make
#  displayName: 'Command Line Script'

- task: MSBuild@1
  displayName: 'Build project PureLayout.Binding'
  inputs:
    solution: PureLayout.Binding/PureLayout.Binding/PureLayout.Net.csproj

    msbuildArchitecture: x64

    configuration: '$(BuildConfiguration)'


- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack

    packagesToPack: PureLayout.Binding/PureLayout.Binding/PureLayout.Net.csproj


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
